feat: greet user
Boar-D-White-Foundation/drone pull request #80
Opened 2024-08-30 20:03 UTC by ollkostin

Implementation for [Greet new joiners ](https://github.com/Boar-D-White-Foundation/drone/issues/78)

2024-08-30 20:17 UTC, frosthamster requested changes

2024-08-30 20:17 UTC, frosthamster commented on README.md
> +curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.60.3
надо полнять и в ci тоже

2024-08-30 20:17 UTC, frosthamster commented on boardwhite/greetings.go
> +func BuildUsername(user *tele.User) (name string) {
это давай в tg унесем в виде `tg.BuildMentionMarkdownV2(user tele.user) string`
и в рейтинге вот это подправим чутка
```
row.UserID = sol.UserID
row.Username = msg.Sender.Username
row.Name = iter.JoinNonEmpty(" ", msg.Sender.FirstName, msg.Sender.LastName)
```

2024-08-30 20:17 UTC, frosthamster commented on boardwhite/greetings.go
> +func (s *Service) makeGreetJoinedUserHandler() func(context.Context, tele.Context) error {
фабрика тут не нужна, просто сделай `OnGreetJoinedUser(ctx context.Context, c tele.Context)`

2024-08-30 20:17 UTC, frosthamster commented on db/badger.go
> -		slog.Error("failed to close badger", err)
`slog.Error("failed to close badger", slog.Any("err", err))`

2024-08-30 20:17 UTC, frosthamster commented on config/config.go
> +	Greetings []string `yaml:"greetings"`
GreetingsTemplates

2024-08-30 20:17 UTC, frosthamster commented on config/config.go
> +		GreetingsThreadId        int   `yaml:"greetings_thread_id"`
давай это лучше сменим на `FloodThreadID`, оно не только для этого может пригодиться

2024-08-30 20:17 UTC, frosthamster commented on boardwhite/greetings.go
> +			return fmt.Errorf("greet user :%w", err)
pick template

2024-08-31 18:29 UTC, ollkostin commented on boardwhite/greetings.go
> +func BuildUsername(user *tele.User) (name string) {
про "унесем" понял, про "в рейтинге вот это подправим" не понял

2024-08-31 20:06 UTC, frosthamster commented on boardwhite/greetings.go
> +func BuildUsername(user *tele.User) (name string) {
ну ты этот код украл с публикации рейтинга, там аналогичная логика ипользуется
вот давай вынесем этот билдер в модуль tg и будем использовать его и тут и в собирании рейтинга

2024-08-31 20:11 UTC, frosthamster commented on boardwhite/greetings.go
> +func BuildUsername(user *tele.User) (name string) {
в сборке рейтинга щас вытаскиваются отдельные поля в каждую строку рейтинга
```
row.UserID = sol.UserID
row.Username = msg.Sender.Username
row.Name = iter.JoinNonEmpty(" ", msg.Sender.FirstName, msg.Sender.LastName)
```

я предлагаю это заменить на что-то типа `row.user = *msg.User`
и потом юзать уже `tg.BuildMentionMarkdownV2(row.User)`

2024-08-31 20:31 UTC, ollkostin commented on README.md
> +curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.60.3
check

2024-08-31 20:31 UTC, ollkostin commented on db/badger.go
> -		slog.Error("failed to close badger", err)
check

2024-08-31 20:32 UTC, ollkostin commented on boardwhite/greetings.go
> +func BuildUsername(user *tele.User) (name string) {
сделал немного иначе, могу переделать, как ты предлагаешь

2024-08-31 20:32 UTC, ollkostin commented on boardwhite/greetings.go
> +func (s *Service) makeGreetJoinedUserHandler() func(context.Context, tele.Context) error {
check

2024-08-31 20:32 UTC, ollkostin commented on boardwhite/greetings.go
> +			return fmt.Errorf("greet user :%w", err)
check

2024-08-31 20:32 UTC, ollkostin commented on config/config.go
> +		GreetingsThreadId        int   `yaml:"greetings_thread_id"`
check

2024-08-31 20:32 UTC, ollkostin commented on config/config.go
> +	Greetings []string `yaml:"greetings"`
check

2024-08-31 20:59 UTC, frosthamster approved these changes
LGTM, good job!

2024-08-31 21:00 UTC, merged